spring.application.name=ticket_management
spring.jpa.hibernate.ddl-auto=validate
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
# Khóa bí mật (Bạn có thể đổi thành chuỗi bất kỳ, miễn là dài hơn 32 ký tự)
jwt.secret=DayLaMotChuoiBiMatCucKyDaiVaAnToanChoDuAnTicket2026
# Thời gian sống của token: 86400000 ms = 24 giờ
jwt.expiration=86400000